Handle NoSuchMethodError exception
这里要使用的两个隐藏的API(getPriority和getPackagePriority)
不幸的是这两个API在Android 8.x中已经被移除了
即使一切顺利，如果无法调用这两个的任何一个API，将会导致"NoSuchMethodError"异常并软重启
我们可以将其中某个API恢复，但这需要反编译&回编译framework.jar，而且不确定因素很大导致实现起来很复杂困难
所以在这里合理地处理这个异常
如果捕获"NoSuchMethodError"，那此方法将返回int值0
这样做可能会导致杀死应用进程变得更加激进，但别无他法

Two hidden APIs to use here (getPriority & getPackagePriority)
Unfortunately these two APIs have been removed in Android 8.x
Even if all goes well, if can't call any of these two APIs, it will cause a "NoSuchMethodError" exception and softreboot.
We can restore one of the APIs, but this requires decompilation & compiling of the framework.jar, and the uncertainties are very complicated and difficult to implement.
So here's a reasonable way to handle this exception
If we catch "NoSuchMethodError", this method will return int value 0
Doing so may cause the killing application process to become more radical, but there is no other way

Exception:

E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: PreventService
E AndroidRuntime: java.lang.NoSuchMethodError: No interface method getPriority(Ljava/lang/String;I)I in class Landroid/app/INotificationManager; or its super classes (declaration of 'android.app.INotificationManager' appears in /system/framework/framework.jar)
    E AndroidRuntime: 	at me.piebridge.prevent.framework.b.a(ActivityReceiver.java:341)
    E AndroidRuntime: 	at me.piebridge.prevent.framework.b.f(ActivityReceiver.java:325)
    E AndroidRuntime: 	at me.piebridge.prevent.framework.h.a(SystemReceiver.java:262)
    E AndroidRuntime: 	at me.piebridge.prevent.framework.h.a(SystemReceiver.java:103)
    E AndroidRuntime: 	at me.piebridge.prevent.framework.h.onReceive(SystemReceiver.java:91)
...